version: '3.9'

services:
  mongodb:
    image: mongo:5.0.10
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  api:
    build:
      context: .
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./application:/app/application